// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VRGameDeals.Data.EF;

namespace VRGameDeals.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200114174201_m10")]
    partial class m10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VRGameDeals.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("VRGameDeals.Data.Models.Platform", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GameGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.HasIndex("GameGuid");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("VRGameDeals.Data.Models.PlatformGame", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("GameGuid");

                    b.HasIndex("PlatformGuid");

                    b.ToTable("PlatformGame");
                });

            modelBuilder.Entity("VRGameDeals.Data.Models.Platform", b =>
                {
                    b.HasOne("VRGameDeals.Data.Models.Game", null)
                        .WithMany("Platforms")
                        .HasForeignKey("GameGuid");
                });

            modelBuilder.Entity("VRGameDeals.Data.Models.PlatformGame", b =>
                {
                    b.HasOne("VRGameDeals.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VRGameDeals.Data.Models.Platform", "Platform")
                        .WithMany("PlatformGames")
                        .HasForeignKey("PlatformGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
